### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by Darkv2** [ph4ge/Dunked-Framework#1]
I downloaded it all an it won't let me open this shit help pls @ph4ge

**Comment by ph4ge** [comment]
the project won't load for you?

**Comment by Darkv2** [comment]
It has error

Den torsdag 28. juli 2016 skrev Phage <notifications@github.com> følgende:

**Comment by polivilas** [comment]
'it has error'

thank u it has been noted

**Comment by ph4ge** [comment]
Closed, no idiots
